CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'log/'
LOG_DIR: 'log/'
SAVE_TOP_K: 3
WORKERS: 4
PRINT_FREQ: 100
LOSS:
  TYPE: false
TRAIN:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 400
  RESUME: true
  OPTIMIZER: adam
  LR: 0.001
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: false
  MULTI_SCALE_FACTOR: 1.5
  IGNORE_LABEL: 255
  MINI_SET: true
TEST:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 1

  MODEL_FILE: ""
