CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: ''
LOG_DIR: ''
WORKERS: 1
PRINT_FREQ: 20
LOSS:
  TYPE: false
TRAIN:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  MULTI_SCALE_FACTOR: 1.5
  IGNORE_LABEL: 255
TEST:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 1

  MODEL_FILE: ""
